### ISSUE TITLE
Woocommerce - Backend product list "language" column css to be fixed

### ISSUE THREAD

**Issue by spleen1981** [qtranslate/qtranslate-xt#804]
As a minor bug, language column in admin product list has 0 width. Maybe a small css rule override could be implemented to reduce the width for one of the woocommerce default columns to let the language column in the table (es th.column-language {width: 5% !important;} )

**Comment by herrvigg** [comment]
But this doesn't sound like a problem of qTranslate, does it? Can you show a screenshot to illustrate?

**Comment by pjrobertson** [comment]
Confirmed.

Adding this CSS will fix the issue:
```css
.fixed .column-language {
width:10%;
}
```
Although for reference, I note that the plugin 'Woocommerce custom shipping status' adds the following CSS which also hides the column. That's an issue for that plugin though

```css
th.manage-column.column-language, td.language.column-language {
        display:none;
}
```
