### ISSUE TITLE
compatibility with acf-autosize

### ISSUE THREAD

**Issue by hirasso** [qtranslate/qtranslate-xt#955]
Hi there! 

When using acf qtranslate fields (e.g. `qtranslate_wysiwyg` and `qtranslate_textarea`) together with the plugin [acf-autosize](https://wordpress.org/plugins/acf-autosize/), the fields that are initially not set to `.current-language` can't be autosized, since they are set to `display: none;`. A quick fix for this would be only hide them visually, not touching the `display` property. This is how I managed to get it to work:

```css
/*
* compatibility with acf-autosize
*/
.acf-field-qtranslate-wysiwyg .multi-language-field > .acf-editor-wrap:not(.current-language),
.acf-field-qtranslate-textarea .multi-language-field > textarea:not(.current-language) {
  position: absolute !important;
  width: 100% !important;
  top: 0 !important;
  left: -10000px !important;
  visibility: hidden !important;
  pointer-events: none !important;
  display: block !important;
}
```
